mariadb:
  container_name: mariadb
  image: mariadb:10.4.8
  ports:
  - "3306"
  environment:
    MYSQL_DATABASE: "keycloak"
    MYSQL_PASSWORD: "password"
    MYSQL_RANDOM_ROOT_PASSWORD: "yes"
    MYSQL_USER: "keycloak"

keycloak:
  container_name: keycloak
  image: quay.io/keycloak/keycloak:15.0.2
  ports:
  - "8080:8080"
  links:
  - mariadb
  - maildev
  volumes:
  - ./.docker-compose/keycloak.env:/etc/secrets/keycloak.env
  - ./unikube/:/opt/jboss/keycloak/themes/unikube/
  environment:
    DB_VENDOR: "mariadb"
    MARIADB_PORT: "3306"
    KEYCLOAK_ENVIRONMENT: "/etc/secrets/keycloak.env"
    KEYCLOAK_PASSWORD: "admin"
    KEYCLOAK_USER: "admin"
    MYSQL_PORT_3306_TCP_ADDR: "mariadb"
    MYSQL_PORT_3306_TCP_PORT: "3306"
    WAIT_ON_ADDR: "mariadb"
    WAIT_ON_PORT: "3306"
  command:
  - -b 0.0.0.0 --server-config=standalone.xml

maildev:
  container_name: maildev
  image: djfarrelly/maildev:1.1.0
  ports:
  - "8081:80"
  - "25"
